/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppAuth: typeof import('./src/components/AppAuth.vue')['default']
    AppView: typeof import('./src/layout/AppView.vue')['default']
    Banner: typeof import('./src/components/Banner.vue')['default']
    CollectionCard: typeof import('./src/components/CollectionCard.vue')['default']
    CollectionsPage: typeof import('./src/pages/CollectionsPage.vue')['default']
    FeaturedMusic: typeof import('./src/components/FeaturedMusic.vue')['default']
    FeaturedMusicCard: typeof import('./src/components/FeaturedMusicCard.vue')['default']
    HeroBanner: typeof import('./src/components/HeroBanner.vue')['default']
    HomePage: typeof import('./src/pages/HomePage.vue')['default']
    IconHeart: typeof import('./src/components/icons/IconHeart.vue')['default']
    IconHeartFill: typeof import('./src/components/icons/IconHeartFill.vue')['default']
    IconHome: typeof import('./src/components/icons/IconHome.vue')['default']
    IconLogout: typeof import('./src/components/icons/IconLogout.vue')['default']
    IconMenu: typeof import('./src/components/icons/IconMenu.vue')['default']
    IconNext: typeof import('./src/components/icons/IconNext.vue')['default']
    IconPlay: typeof import('./src/components/icons/IconPlay.vue')['default']
    IconPlaylist: typeof import('./src/components/icons/IconPlaylist.vue')['default']
    IconProfile: typeof import('./src/components/icons/IconProfile.vue')['default']
    IconRadio: typeof import('./src/components/icons/IconRadio.vue')['default']
    IconRepeatOne: typeof import('./src/components/icons/IconRepeatOne.vue')['default']
    IconSearch: typeof import('./src/components/icons/IconSearch.vue')['default']
    IconShuffle: typeof import('./src/components/icons/IconShuffle.vue')['default']
    IconVideo: typeof import('./src/components/icons/IconVideo.vue')['default']
    IconVolume: typeof import('./src/components/icons/IconVolume.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    MusicayLogo: typeof import('./src/components/icons/MusicayLogo.vue')['default']
    MusicUpload: typeof import('./src/components/MusicUpload.vue')['default']
    NotFoundPage: typeof import('./src/pages/NotFoundPage.vue')['default']
    PanelTop: typeof import('./src/components/PanelTop.vue')['default']
    Player: typeof import('./src/components/Player.vue')['default']
    ProfilePage: typeof import('./src/pages/ProfilePage.vue')['default']
    RegistrationForm: typeof import('./src/components/RegistrationForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/SearchBar.vue')['default']
    Sidenav: typeof import('./src/components/Sidenav.vue')['default']
    SideNav: typeof import('./src/components/SideNav.vue')['default']
    SingleMusicPage: typeof import('./src/pages/SingleMusicPage.vue')['default']
    TopCharts: typeof import('./src/components/TopCharts.vue')['default']
    TopChartsCard: typeof import('./src/components/TopChartsCard.vue')['default']
    View: typeof import('./src/layout/View.vue')['default']
  }
}
